name: inway
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4
  fl_country_code_picker: ^0.0.2+1
  pinput: ^2.2.12
  firebase_core: ^2.6.1
  firebase_auth: ^4.2.8
  image_picker: ^1.0.0
  cloud_firestore: ^4.4.2
  firebase_storage: ^11.0.13
  flutter_credit_card: ^3.0.7
  modal_progress_hud: ^0.1.3
  awesome_dialog: ^1.1.3
  validators: ^2.0.0
  google_sign_in: ^5.1.0
  shared_preferences: ^2.2.2
  provider: ^4.3.2+4
  flushbar: ^1.10.4
  http: ^0.13.6
  api_cache_manager: ^1.0.2
  nb_utils: ^6.0.6
  dots_indicator: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter_icons:
 android: true
 ios: true
 remove_alpha_ios: true
 image_path: "images/banking/Unics-logo.jpg"

flutter:
  uses-material-design: true

  
  assets:
    - assets/images/
    - fonts/
    - images/banking/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic
        - asset: fonts/Raleway-ExtraBold.ttf
          weight: 800
        - asset: fonts/Raleway-Light.ttf
          weight: 300
        - asset: fonts/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/Raleway-SemiBold.ttf
          weight: 600
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
