// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQKNmwb1TJa0OKh4hNO-hdRcXlr9_U34A',
    appId: '1:175695184617:web:d42c82761d163cc03ee678',
    messagingSenderId: '175695184617',
    projectId: 'citycab-1af2b',
    authDomain: 'citycab-1af2b.firebaseapp.com',
    storageBucket: 'citycab-1af2b.appspot.com',
    measurementId: 'G-10TRRN9BZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtOg_XQqJ34QtNO-jEd88GaDr9btNTJ-k',
    appId: '1:175695184617:android:14efa498c204a4cc3ee678',
    messagingSenderId: '175695184617',
    projectId: 'citycab-1af2b',
    storageBucket: 'citycab-1af2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkn4qe_xwfIY73G2sqvdjGRZ9OfDd1LWs',
    appId: '1:175695184617:ios:e8dbf3f19509d48f3ee678',
    messagingSenderId: '175695184617',
    projectId: 'citycab-1af2b',
    storageBucket: 'citycab-1af2b.appspot.com',
    androidClientId: '175695184617-iu9b7bcarsc6ajb9svohm2jqjd8do150.apps.googleusercontent.com',
    iosClientId: '175695184617-qv4q6j13urb4m505jcm9bvucmnn86b6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.inway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkn4qe_xwfIY73G2sqvdjGRZ9OfDd1LWs',
    appId: '1:175695184617:ios:e8dbf3f19509d48f3ee678',
    messagingSenderId: '175695184617',
    projectId: 'citycab-1af2b',
    storageBucket: 'citycab-1af2b.appspot.com',
    androidClientId: '175695184617-iu9b7bcarsc6ajb9svohm2jqjd8do150.apps.googleusercontent.com',
    iosClientId: '175695184617-qv4q6j13urb4m505jcm9bvucmnn86b6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.inway',
  );
}
